# kubernetes/iot-sensor-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-sensor-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-sensor
  template:
    metadata:
      labels:
        app: iot-sensor
    spec:
      containers:
      - name: iot-sensor
        image: iot-sensor
        imagePullPolicy: Never