# kubernetes/design-db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: design-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design-db
  template:
    metadata:
      labels:
        app: design-db
    spec:
      containers:
      - name: design-db
        image: design-db
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: design-db-service # This name is how other pods will find it
spec:
  selector:
    app: design-db # Selects pods with the label "app: design-db"
  ports:
    - protocol: TCP
      port: 5003       # The port the service is available on
      targetPort: 5003 # The port the container is listening on